# Generated by Django 4.1.7 on 2023-02-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(blank=True, upload_to='cars'),
        ),
        migrations.AddField(
            model_name='car',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CarPicture',
        ),
    ]
