# Generated by Django 4.1.7 on 2023-02-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_delete_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
